name: "Repo Issue"
description: "Report validation/indexing issues"
title: "[Repo] <Short description>"
labels:
  - "repo"
body:
  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "Describe the problem and steps to reproduce"
