name: "Improve Answer"
description: "Suggest improvements to an existing answer"
title: "[Improve] Q#### <Short title>"
labels:
  - "type:improvement"
body:
  - type: input
    id: question-id
    attributes:
      label: "Question ID (Q####)"
      placeholder: "Q0401"
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: "Your proposed change"
      description: "What to add, fix, or clarify"
